name: 'Issue Reference'
on: 
  issues:
    types: [opened]

jobs:
  change_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
      - run: sudo apt-add-repository https://cli.github.com/packages
      - run: sudo apt update
      - run: sudo apt install gh
      
